### ISSUE TITLE
Fail to parse outputs for biome code block

### ISSUE THREAD

**Issue by RShirohara** [mongolyy/reviewdog-action-biome#20]
### Summary

この Action を私のリポジトリ (RShirohara/unified-webnovel#227) に導入してみたところ、GitHub Checks レポーターの出力が壊れています。

[GitHub Checks レポーターの出力](https://github.com/RShirohara/unified-webnovel/runs/20683019713) を確認したところ、Biome が出力するコードブロックの最終行が空行ではない場合に、Markdown のコードブロック記号 (` ``` `) が生成されていないようです。  
リポジトリ内へ[スクリプトを移植](https://github.com/RShirohara/unified-webnovel/pull/227/commits/9c85b9957f1a459ab14c4c4f7b5ca1433ac1f017)し sed 正規表現を以下のように書き換えてみたところ、正常に Markdown コードブロックが出力されるようになりました。

```diff
    "$(npm root)"/.bin/biome check --apply ${INPUT_BIOME_FLAGS} 2>&1 1>/dev/null |
      sed 's/ *$//' |
-     sed -z 's/\n\n\([^\n]*│[^\n]*\)/\n\n  ```\n\1/g' |
-     sed -z 's/│\n\n/│\n  ```\n/g' |
+     sed -z 's/\n\n\([^\n]*│\)/\n\n  ```\n\1/g' |
+     sed -z 's/\(│[^\n]*\)\n\n/\1\n  ```\n\n/g' |
      reviewdog \
```

### Expected Behavior

Biome が出力するコードブロックの最終行が空行ではない場合、Markdown コードブロックが正しく生成されない。

- Reporter output: <https://github.com/RShirohara/unified-webnovel/runs/20683019713>

![image](https://github.com/mongolyy/reviewdog-action-biome/assets/47940764/bc8870a3-dfbe-48b9-9df4-166d06d8f32a)

### Actual Behavior

Biome が出力するコードブロックの最終行が空行ではない場合でも、Markdown コードブロックとして表示される。

- Reporter output: <https://github.com/RShirohara/unified-webnovel/runs/20683507837>
- Reviewdog output (`-tee` オプションを使用): <https://github.com/RShirohara/unified-webnovel/actions/runs/7593238551/job/20683503878#step:6:29>

![image](https://github.com/mongolyy/reviewdog-action-biome/assets/47940764/5ef4ae0a-fa42-4334-bb33-26ada0c0e413)

**Comment by mongolyy** [comment]
@RShirohara 

Issueの作成、並びにsedコマンドの修正提案までご丁寧にありがとうございます。
#21 で修正し、v1.0.1としてgithub actionsをリリースしました。
v1やv1.0も同時に更新しています。
ご確認ください。
何かあれば、このissueにコメントいただき、issueを再オープンしてください。

引き続きよろしくお願いします。

**Comment by RShirohara** [comment]
@mongolyy 

早速の対応ありがとうございます。
[v1.0.1 を適用](https://github.com/RShirohara/unified-webnovel/pull/227/commits/1ed6f4c17758cd4676f1d52111061133f95177dc)して再実行したところ、上記の問題が修正されていることは確認できました。

- Reporter output: <https://github.com/RShirohara/unified-webnovel/runs/20686360984>

![image](https://github.com/mongolyy/reviewdog-action-biome/assets/47940764/a73f51ad-d574-423b-a58b-de7b392ee702)

ただ、上記とは異なる出力の場合に同じ問題が発生していることも確認しました。  
レポーターの出力を確認したところ、Biome コマンドブロックの直後に `~ more lines truncated` が出力されているようです。

![image](https://github.com/mongolyy/reviewdog-action-biome/assets/47940764/176796b7-84e3-4d74-a657-dca5317725a5)

Biome 側の実装 [crates/biome_diagnostics/src/display/diff.rs#L597](https://github.com/biomejs/biome/blob/main/crates/biome_diagnostics/src/display/diff.rs#L597) を確認したところ、差分が 150 行を超える場合に上記のメッセージが出力されるケースが存在するようです。
(Biome は今のところ実行するたびに出力がランダムに変わるケースがあるようで、提案した正規表現を作成したタイミングでは上記の挙動を確認できていませんでした……)

**Comment by RShirohara** [comment]
また、PR で Fixed としてマージされた issue は作成者から再オープンできないようでした。

![image](https://github.com/mongolyy/reviewdog-action-biome/assets/47940764/e54260f1-1ec6-47ef-8484-296f3fa85bca)

**Comment by mongolyy** [comment]
@RShirohara 

https://github.com/mongolyy/reviewdog-action-biome/pull/22 にて `N more lines truncated` のパターンの再現を確認しました
そのうえで、│を含むブロックをコードブロックとして扱うようにawkコマンドで書き換えました
（sedでも可能かもしれませんが、awkで書いた方がシンプルに書けそうでしたので）

v1.0.3としてリリースしているので、お手数をおかけしますが動作確認していただけますでしょうか？

また何かあればコメントいただくか、新しいIssueを作成していただけると幸いです

引き続いよろしくお願いします！

**Comment by RShirohara** [comment]
@mongolyy 
対応いただきありがとうございます!

`N more lines truncated` のパターンで正常にコードブロックが生成されていることを確認できました。

- Reporter output: <https://github.com/RShirohara/unified-webnovel/actions/runs/7626813843/job/20774237391>

![image](https://github.com/mongolyy/reviewdog-action-biome/assets/47940764/8258e2cf-8390-4eec-bfc1-a2342e7e02e5)
